In [2]:
import numpy as np
arr = np.array([2,423,6,7,8,3])
print(arr)
arr.ndim
print(arr.ndim)
arr.argmax()
print(arr.argmax)
arr.argmin()
print(arr.argmin)
arr.shape
print(arr.shape)
arr.size
print(arr.size)
arr.dtype
print(arr.dtype)
reshape = arr.reshape(2,3)
print(reshape)
r = np.mean(arr)
print(r)
t = np.median(arr)
print(t)
arr[2:5]

[  2 423   6   7   8   3]
1
<built-in method argmax of numpy.ndarray object at 0x000001D62D550870>
<built-in method argmin of numpy.ndarray object at 0x000001D62D550870>
(6,)
6
int64
[[  2 423   6]
 [  7   8   3]]
74.83333333333333
6.5


array([6, 7, 8])

In [26]:
a = np.array([2, 3, 4], dtype=float)
print(a)
b = np.array([5, 6, 7])
print(b)
print(b.dtype)
c_unsigned32 = a - b
print('unsigned c:', c_unsigned32, c_unsigned32.dtype)
c_signed32 = a - b.astype(np.int32)
print('signed c:', c_signed32, c_signed32.dtype)

[2. 3. 4.]
[5 6 7]
int64
unsigned c: [-3. -3. -3.] float64
signed c: [-3. -3. -3.] float64


In [31]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. ])

In [ ]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [ ]:
a = np.eye(3)
print(a)
b = np.eye(3, 5)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
