In [11]:
# Array creatiom
import numpy as np
arr = np.array([2,4,5,6,7,8,9,23])
print(arr)
arr.dtype
print(arr.dtype)

[ 2  4  5  6  7  8  9 23]
int64


In [ ]:
# 2D
x = np.eye(3)
print(x)
y = np.eye(4 , k = 1)
print(y)
z = np.eye(3, 5)
print(z)
a = np.diag([1, 2, 3])
print(a)
x1 = np.diag([1, 2, 3], 1)
print(x1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]


In [22]:
x = np.vander(np.linspace(0, 2, 5), 2)
print(x)
x1 = np.vander([1, 2, 3, 4], 2)
print(x1)

[[0.  1. ]
 [0.5 1. ]
 [1.  1. ]
 [1.5 1. ]
 [2.  1. ]]
[[1 1]
 [2 1]
 [3 1]
 [4 1]]


In [ ]:
import numpy as np
arr = np.array([3,5,7,8,2,1,56,78])
print(arr)
reshape  = arr.reshape(2,4)
print(reshape)
np.append(arr,9)
np.insert
# print(arr)

[ 3  5  7  8  2  1 56 78]
[[ 3  5  7  8]
 [ 2  1 56 78]]


array([ 3,  5,  7,  8,  2,  1, 56, 78,  9])

In [ ]:
import numpy as np

arr1 = np.array([[[3,5,2,1],[2,5,3,4]]])
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print("Array 1 =",arr)
arr3 = arr1 + arr2
print("Array 2 =",arr3)
arr1 * 3
print("Array 3 =",arr1)
arr2 + 6
print("Array 4 =",arr2.astype(float))
arr3 / 2
print("Array 5 =",arr3.astype(int))
arr1.argmax()
print(arr1.argmax())
# np.concatenate(((arr1 , arr2)))
arr1.flatten()

Array 1 = [[ 3  5 23 67]
 [ 2  5 67 45]]
Array 2 = [[[ 4  7  5  5]
  [ 7 11 10 12]]]
Array 3 = [[[3 5 2 1]
  [2 5 3 4]]]
Array 4 = [[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
Array 5 = [[[ 4  7  5  5]
  [ 7 11 10 12]]]
1
[[ 3  5 23 67]
 [ 2  5 67 45]]


In [76]:
import numpy as np

# Create a 3D array (2 layers, 3 rows, 4 columns)
arr_3d = np.array([
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]],
    
    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])
print("3D array shape:", arr_3d.shape)  # (2, 3, 4)
print("3D array:")
print(arr_3d)

# Convert to 2D by flattening last two dimensions
arr_2d = arr_3d.reshape(2, -1)  # (2, 12)
print("\n2D array (2x12):")
print(arr_2d)
print("New shape:", arr_2d.shape)  # (2, 12)

arr_3d.flatten()

3D array shape: (2, 3, 4)
3D array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

2D array (2x12):
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
New shape: (2, 12)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])